# -*- coding: utf-8 -*-
"""WebScrapping (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13d3du-9euh01c_K8ptoy5QILqjV2Bhs6
"""

import requests
from bs4 import BeautifulSoup

url = "https://store.bigassfans.com/en_us/for-the-home"

response = requests.get(url)
response

soup = BeautifulSoup(response.text)
soup

print(soup.prettify())

img_url = []

for img in soup.find_all("img", class_="product-image-photo"):
  img_url.append(img["src"])

img_url

product_name = []
for a in soup.find_all("a", class_="product-item-link"):
    text = a.get_text(strip=True)
    if text:
        product_name.append(text)

product_name



product_prices = []

for p in soup.find_all("span", class_="price"):
    text = p.get_text(strip=True)
    # just change symbol, no conversion:
    text = text.replace("$", " ")
    product_prices.append(text)

product_prices

for name ,image, price in zip(product_name, img_url,product_prices):
  print("|", name, "|", image, "|", price, "|")

import pandas as pd

min_len = min(len(product_name), len(img_url),  len(product_prices))

df = pd.DataFrame({
    "Product Name": product_name[:min_len],
    "Image Url": img_url[:min_len],
    "Price": product_prices[:min_len]
})

df

df.to_csv("data.csv",index=False)
display(df)

from google.colab import files
files.download('data.csv')

